version: '3'

services:
  web:
    build: .
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_MYSQL_HOST: "database"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_NAME: "avideo"
      DB_MYSQL_USER: "avideo"
      DB_MYSQL_PASSWORD: "avideo"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      SERVER_NAME: "localhost"
      ENABLE_PHPMYADMIN: "yes"
      CREATE_TLS_CERTIFICATE: "yes"
      TLS_CERTIFICATE_FILE: "/etc/apache2/ssl/localhost.crt"
      TLS_CERTIFICATE_KEY: "/etc/apache2/ssl/localhost.key"
      CONTACT_EMAIL: "admin@localhost"
      SYSTEM_ADMIN_PASSWORD: "password"
      WEBSITE_TITLE: "AVideo"
      MAIN_LANGUAGE: "en_US"
    volumes:
      - "./var/www/avideo:/var/www/avideo"
    depends_on:
      - database
      - phpmyadmin
    networks:
      - app_net

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    restart: "unless-stopped"
    environment:
      PMA_ABSOLUTE_URI: "https://localhost/phpmyadmin"
      PMA_HOST: "database"
      PMA_PORT: 3306
      PMA_CONTROLUSER: "avideo"
      PMA_CONTROLPASS: "avideo"
      PMA_PMADB: "avideo"
      HIDE_PHP_VERSION: "true"
    depends_on:
      - database
    networks:
      - app_net

  database:
    image: "mariadb:latest"
    restart: "unless-stopped"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DATABASE: "avideo"
      MYSQL_USER: "avideo"
      MYSQL_PASSWORD: "avideo"
    volumes:
      - ./.compose/db:/var/lib/mysql
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
